[project]
name = "dautien-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.0.0",
    "huggingface-hub>=0.34.4",
    "ipykernel>=6.30.1",
    "torch>=2.8.0",
    "transformers>=4.55.2",
    "unsloth>=2025.7.2",
]
